{% set python_min = "3.10" %}
{% set name = "felyx-distributed" %}
{% set version = "1.0.4" %}

package: 
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.ifremer.fr/felyx/felyx_distributed/-/archive/{{ version }}/felyx_distributed-{{ version }}.tar.gz
  sha256: 096ef5e6a9e1859f2f1b06a5f7a29657dd7ecf322c6d8d24abb736a8ce6638af
  
build:
  noarch: python
  script_env:
    - POETRY_DYNAMIC_VERSIONING_BYPASS={{ version }}
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  noarch: python
  entry_points:
    - felyx-mmdb = felyx_distributed.main.run_mmdb:felyx_mmdb

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning >=1.0.0,<2.0.0
    - pip
  run:
    - python >={{ python_min }}
    - pip
    - felyx-processor >=2.5.8,<3.0.0
    - jobard-client >=1.6.0,<1.7.0
    - pydantic-settings >=2.4.0,<3.0.0

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - felyx_distributed
    
about:
  home: https://gitlab.ifremer.fr/felyx/felyx_distributed
  license: LGPL-3.0-only
  license_file: LICENSE.md
  summary: Companion to create MMDBs by launching felyx-extraction and felyx-assemble commands with or without Jobard.

extra:
  recipe-maintainers:
    - erwanbodere
    - criou-cg
    - cso2943
    - Marie59
    - jfpiolle
    
